# Generated by Django 5.2.4 on 2026-07-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_calorie_post_carbohydrate_post_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(blank=True, max_length=200, verbose_name='상품 종류 해시태그'),
        ),
    ]
