# Generated by Django 6.0.6 on 2026-07-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_actor_review_running_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('comedy', '코미디'), ('romance', '로맨스'), ('thriller', '스릴러'), ('horror', '공포'), ('sf', 'SF'), ('animation', '애니메이션'), ('drama', '드라마'), ('documentary', '다큐멘터리')], max_length=20),
        ),
    ]
